const yearsGoverned = new Date().getFullYear() - 1949;

export const CASES = [
  {id:'ukraine',r:'european',flag:'\u{1F1FA}\u{1F1E6}',abs:'"Russian Kyiv"',real:'Ukraine',cl:'Russia',yr:'Ongoing since 2022',
   sh:'Russia claims Ukraine is "historically" its territory — the same argument China uses for Taiwan. Would the world accept Ukraine competing as "Russian Kyiv"?',
   full:'<p>Russia\'s justification for invading Ukraine mirrors Beijing\'s position on Taiwan: <span class="pw">Ukraine is historically Russian territory</span>. Yet no one forces Ukraine to compete under an imposed name.</p><p>If this logic fails for Ukraine — why does the world accept it for Taiwan?</p>',
   cmp:{t:'Ukraine forced to compete as "Russian Kyiv"?',u:'"Chinese Taipei" — Taiwan\'s actual situation'}},
  {id:'greece',r:'european',flag:'\u{1F1EC}\u{1F1F7}',abs:'"Ottoman Athens"',real:'Greece',cl:'Ottoman Empire (modern Turkey)',yr:'400 years of Ottoman rule',
   sh:'The Ottoman Empire actually governed Greece for 400 years. China has never governed Taiwan. If "Ottoman Athens" is unacceptable — why is "Chinese Taipei" accepted?',
   full:'<p>The Ottoman Empire <span class="pw">actually administered Greece for roughly 400 years</span> — from 1453 to 1821. China has never governed Taiwan as the PRC, which was founded in 1949.</p><p>"Ottoman Athens" would at least be historically grounded. "Chinese Taipei" is not even that.</p>',
   cmp:{t:'Greece never forced to use "Ottoman Athens"',u:'"Chinese Taipei" — historically weaker, globally accepted'}},
  {id:'estonia',r:'european',flag:'\u{1F1EA}\u{1F1EA}',abs:'"Soviet Tallinn"',real:'Estonia',cl:'Soviet Union',yr:'Occupied 1940–1991',
   sh:'Estonia was occupied by the USSR for 51 years. When it re-declared independence in 1991, no negotiation over its name was needed. Taiwan has governed itself longer — why is it different?',
   full:'<p>Estonia was incorporated into the Soviet Union in 1940. For <span class="pw">51 years, many countries never legally recognised Soviet annexation</span>.</p><p>When Estonia re-declared independence in 1991, it did not negotiate its name. Taiwan has self-governed since 1949 — longer than Estonia\'s entire occupation — yet still competes under a fabricated name.</p>',
   cmp:{t:'Estonia reclaimed its name in 1991',u:'Taiwan still uses "Chinese Taipei" today'}},
  {id:'latvia',r:'european',flag:'\u{1F1F1}\u{1F1FB}',abs:'"Soviet Riga"',real:'Latvia',cl:'Soviet Union',yr:'Occupied 1940–1991',
   sh:'The West maintained non-recognition of Soviet Baltic annexation for 50 years — a principled stand it has never applied to Taiwan. Why the difference?',
   full:'<p>Western nations maintained <span class="pw">non-recognition of Soviet Baltic annexation</span> throughout the Cold War, keeping Baltic diplomats in Washington.</p><p>That same principle — that a powerful neighbour\'s claim does not erase a nation\'s identity — has not been applied to Taiwan. Why not?</p>',
   cmp:{t:'West refused to recognise Soviet claim on Latvia',u:'Same West accepts "Chinese Taipei"'}},
  {id:'lithuania',r:'european',flag:'\u{1F1F1}\u{1F1F9}',abs:'"Soviet Vilnius"',real:'Lithuania',cl:'Soviet Union',yr:'Occupied 1940–1991',
   sh:'Lithuania allows Taiwan to use "Taiwan" in its representative office name. Why does Lithuania understand this — when many larger nations do not?',
   full:'<p>In 2021, Lithuania <span class="pw">allowed Taiwan to open a representative office under the name "Taiwan"</span> — triggering massive Chinese economic pressure. Vilnius held firm.</p><p>Because Lithuanians remember what it means to fight for your name. Does the rest of the world?</p>',
   cmp:{t:'Lithuania fought for its own name — and supports Taiwan\'s',u:'"Chinese Taipei" — what Lithuania refuses to accept'}},
  {id:'poland',r:'european',flag:'\u{1F1F5}\u{1F1F1}',abs:'"Russian Warsaw"',real:'Poland',cl:'Russia / Prussia / Austria',yr:'Partitioned 1772–1918',
   sh:'Poland was erased from the map for 123 years. When reborn in 1918, no one questioned its name. Should Taiwan\'s identity be treated differently?',
   full:'<p>Poland was partitioned three times and <span class="pw">ceased to exist as a state for 123 years</span>. Yet Polish identity survived. When reborn in 1918, no one questioned its name.</p><p>Taiwan\'s identity has survived decades of international erasure. Should it not receive the same recognition?</p>',
   cmp:{t:'Poland reborn with its own name after 123 years',u:`Taiwan self-governing ${yearsGoverned} years, still "Chinese Taipei"`}},
  {id:'finland',r:'european',flag:'\u{1F1EB}\u{1F1EE}',abs:'"Russian Helsinki"',real:'Finland',cl:'Russian Empire / USSR',yr:'Russian rule 1809–1917',
   sh:'Finland was a Grand Duchy of Russia for 109 years, then survived the Winter War. Would "Russian Helsinki" ever be acceptable?',
   full:`<p>Finland was under Russian rule for 109 years. In 1939, the Soviet Union invaded — <span class="pw">the Winter War killed over 160,000 Finns</span> defending their sovereignty.</p><p>Finland is now a NATO member. No one calls its capital "Russian Helsinki." Does Taiwan's ${yearsGoverned} years of democracy deserve the same honour?</p>`,
   cmp:{t:'Finland\'s sovereignty respected after the Winter War',u:'Taiwan\'s sovereignty erased into "Chinese Taipei"'}},
  {id:'norway',r:'european',flag:'\u{1F1F3}\u{1F1F4}',abs:'"Swedish Oslo"',real:'Norway',cl:'Sweden / Denmark',yr:'Union with Sweden 1814–1905',
   sh:'Norway was under Danish rule for 400 years, then Swedish for nearly a century. Its 1905 independence by referendum was respected globally. Why should Taiwan\'s self-determination be different?',
   full:'<p>Norway spent <span class="pw">over 400 years under Danish rule</span>, then nearly a century in union with Sweden. Its 1905 independence by referendum was a landmark for self-determination.</p><p>Taiwan has held democratic elections since 1996. Should that not count?</p>',
   cmp:{t:'Norwegian referendum on independence respected globally',u:'Taiwanese identity polls dismissed internationally'}},
  {id:'denmark',r:'european',flag:'\u{1F1E9}\u{1F1F0}',abs:'"German Copenhagen"',real:'Denmark',cl:'Nazi Germany',yr:'Occupied 1940–1945',
   sh:'Germany occupied Denmark for 5 years. Today "German Copenhagen" would be deeply offensive. If 5 years of occupation does not justify renaming — what about zero days?',
   full:'<p>Nazi Germany occupied Denmark from 1940 to 1945. <span class="pw">The occupation remains a defining national memory</span> for Danes.</p><p>Calling Copenhagen "German Copenhagen" would be considered deeply offensive. Yet Taiwan — never governed by the PRC — is asked to accept "Chinese Taipei." Five years of occupation does not justify renaming. Neither does zero days.</p>',
   cmp:{t:'"German Copenhagen" — offensive after 5 years of occupation',u:'"Chinese Taipei" — accepted despite zero days of PRC rule'}},
  {id:'iceland',r:'european',flag:'\u{1F1EE}\u{1F1F8}',abs:'"Danish Reykjavik"',real:'Iceland',cl:'Denmark',yr:'500 years of Danish rule · Independent 1944',
   sh:'Iceland was ruled by Denmark for 500 years — longer than any period in Taiwan\'s history. It declared independence in 1944. No one questions Reykjavik today. Why should Taipei need a prefix?',
   full:'<p>Iceland was under Danish rule for roughly <span class="pw">500 years</span>, one of the longest colonial relationships in Nordic history. It declared independence in 1944.</p><p>Today, no one calls Reykjavik "Danish Reykjavik." Taiwan has governed itself since 1949. Does a capital city need a foreign prefix to be legitimate?</p>',
   cmp:{t:'"Danish Reykjavik" — absurd after 500 years of rule',u:'"Chinese Taipei" — imposed despite zero PRC governance'}},
  {id:'ireland',r:'european',flag:'\u{1F1EE}\u{1F1EA}',abs:'"British Dublin"',real:'Ireland',cl:'Britain',yr:'~800 years of British rule',
   sh:'How would an Irish person react to "British Dublin"? Is that reaction different from how Taiwanese people feel about "Chinese Taipei"?',
   full:'<p>Ireland endured roughly 800 years of British presence. The <span class="pw">fight for Irish identity</span> — its language, culture, and name — was one of the defining struggles of the 20th century.</p><p>"British Dublin" would be a profound insult. Does "Chinese Taipei" carry the same weight for Taiwan?</p>',
   cmp:{t:'"British Dublin" — universally recognised as insulting',u:'"Chinese Taipei" — accepted without question'}},
  {id:'algeria',r:'european',flag:'\u{1F1E9}\u{1F1FF}',abs:'"French Algiers"',real:'Algeria',cl:'France',yr:'132 years of French colonisation',
   sh:'France called Algeria an integral part of France — not a colony, a "department." Algeria fought a brutal war for its name. Should Taiwan have to do the same?',
   full:`<p>France did not consider Algeria a colony — it was officially a <span class="pw">department of France</span>, as integral as Normandy. This framing denied Algerian self-determination for 132 years.</p><p>Algeria won independence in 1962 after a brutal war. Taiwan has self-governed peacefully for ${yearsGoverned} years. Should peaceful self-governance count for less than armed struggle?</p>`,
   cmp:{t:"Algeria's independence recognised after war",u:`Taiwan's self-governance ignored after ${yearsGoverned} years`}},
  {id:'vietnam',r:'asian',flag:'\u{1F1FB}\u{1F1F3}',abs:'"French Hanoi"',real:'Vietnam',cl:'France',yr:'~100 years of French rule',
   sh:'France ruled Vietnam for nearly a century. Would "French Hanoi" feel right to Vietnamese people today?',
   full:`<p>France colonised Vietnam in stages, eventually controlling the entire country as <span class="pw">French Indochina</span>. Vietnam endured nearly 100 years of colonial rule before independence in 1945.</p><p>"French Hanoi" would be considered deeply offensive across Southeast Asia. Taiwan has self-governed for ${yearsGoverned} years — is "Chinese Taipei" any different?</p>`,
   cmp:{t:'"French Hanoi" — offensive to all Vietnamese',u:'"Chinese Taipei" — imposed on a self-governing democracy'}},
  {id:'india',r:'asian',flag:'\u{1F1EE}\u{1F1F3}',abs:'"British Delhi"',real:'India',cl:'Britain',yr:'~200 years of British rule',
   sh:'India is the world\'s largest democracy, independent since 1947. Would "British Delhi" be acceptable today? What makes "Chinese Taipei" different?',
   full:'<p>Britain ruled India for roughly 200 years. Indian independence in 1947 was one of the most significant decolonisation moments in history. <span class="pw">The right to self-determination</span> was central to India\'s founding story.</p><p>No one calls its capital "British Delhi." Taiwan is Asia\'s most established Chinese-speaking democracy. Why does one democracy get its name, and not the other?</p>',
   cmp:{t:'"British Delhi" — unthinkable for the world\'s largest democracy',u:'"Chinese Taipei" — imposed on Asia\'s Chinese-speaking democracy'}},
  {id:'malaysia',r:'asian',flag:'\u{1F1F2}\u{1F1FE}',abs:'"British Kuala Lumpur"',real:'Malaysia',cl:'Britain',yr:'British rule until 1957',
   sh:'Malaysia gained independence from Britain in 1957. No one calls its capital "British Kuala Lumpur." Many Taiwanese live in Malaysia — does this parallel resonate?',
   full:'<p>Malaysia was under British colonial control until 1957. <span class="pw">Merdeka — independence</span> — remains the defining national value.</p><p>A large Taiwanese diaspora lives in Malaysia. When Taiwanese in Kuala Lumpur explain "Chinese Taipei," Malaysians who know the frustration of colonial naming often understand immediately.</p>',
   cmp:{t:'"British Kuala Lumpur" — absurd after 1957 independence',u:'"Chinese Taipei" — still used for a self-governing democracy'}},
  {id:'mexico',r:'american',flag:'\u{1F1F2}\u{1F1FD}',abs:'"Spanish Mexico City"',real:'Mexico',cl:'Spain',yr:'300 years of Spanish rule',
   sh:'Spain ruled Mexico for three centuries. Mexico won independence in 1821. No one calls its capital "Spanish Mexico City." Can national identity be erased by a former ruler\'s claim?',
   full:`<p>Spain governed Mexico for <span class="pw">nearly 300 years</span>. Mexican independence in 1821 reclaimed not just territory but identity — the right to be named on one's own terms.</p><p>No one disputes "Mexico City." Yet Taiwan, self-governing democratically for ${yearsGoverned} years, is still denied its name in most international contexts.</p>`,
   cmp:{t:"Mexico's name reclaimed after independence in 1821",u:`Taiwan's name still held hostage after ${yearsGoverned} years`}},
  {id:'usa',r:'american',flag:'🇺🇸',abs:'"British Washington D.C."',real:'United States',cl:'Britain',yr:'Colonial rule until 1776',
   sh:'The US declared independence from Britain in 1776 — self-determination is foundational to American identity. Would Americans accept competing internationally as "British Washington D.C."?',
   full:'<p>The United States fought a war of independence against Britain, founding its identity on the principle that <span class="pw">people have the right to determine their own government and name</span>. That principle is written into the Declaration of Independence.</p><p>Taiwan has self-governed democratically since 1949 — longer than many nations that are fully recognised today. If self-determination justified America\'s independence in 1776, why doesn\'t it justify Taiwan\'s name in 2026?</p>',
   cmp:{t:'"British Washington D.C." — unthinkable for a country founded on self-determination',u:`"Chinese Taipei" — imposed on a democracy that has governed itself for ${yearsGoverned} years`}},
  {id:'mongolia',r:'special',flag:'\u{1F1E8}\u{1F1F3}',abs:'"Mongolian Beijing"',real:'China (reversed)',cl:'Mongol Empire / Yuan Dynasty',yr:'Yuan Dynasty ruled China 1271–1368',
   sh:'The Mongol Empire built Beijing and ruled China for nearly 100 years. By China\'s own logic — shouldn\'t Beijing be called "Mongolian Beijing"?',
   full:'<p>The Mongol Empire — under Kublai Khan — <span class="pw">conquered China and founded the Yuan Dynasty</span>, ruling from 1271 to 1368. Beijing was built and designated as the imperial capital by the Mongols.</p><p>By the same logic China uses to claim Taiwan — that historical connection justifies a naming right — shouldn\'t Beijing be "Mongolian Beijing"? The Mongols actually ruled China for ~100 years. The PRC has never governed Taiwan for a single day.</p>',
   cmp:{t:'Mongols actually built and ruled Beijing for ~100 years',u:'PRC has never governed Taiwan for a single day'}}
];
